# action.yml
name: CI

description: 'CI Action'

inputs:
  github_token:
    description: github_token
    required: true
  email_token:
    description: Email token
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    EMAIL_TOKEN: ${{ inputs.email_token }}